// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHouse = "houses"

// House mapped from table <houses>
type House struct {
	ID          int32          `gorm:"column:id;primaryKey" json:"id"`
	Code        string         `gorm:"column:code" json:"code"`
	Name        string         `gorm:"column:name" json:"name"`
	PlantTotal  int32          `gorm:"column:plant_total" json:"plant_total"`
	Temperature float64        `gorm:"column:temperature" json:"temperature"`
	Humidity    float64        `gorm:"column:humidity" json:"humidity"`
	Light       string         `gorm:"column:light" json:"light"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName House's table name
func (*House) TableName() string {
	return TableNameHouse
}
