// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHouseLog = "house_logs"

// HouseLog mapped from table <house_logs>
type HouseLog struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	HouseID        int32     `gorm:"column:house_id" json:"house_id"`
	LightStart     time.Time `gorm:"column:light_start" json:"light_start"`
	LightStop      time.Time `gorm:"column:light_stop" json:"light_stop"`
	Co2            float64   `gorm:"column:co2" json:"co2"`
	Temperature    float64   `gorm:"column:temperature" json:"temperature"`
	Humidity       float64   `gorm:"column:humidity" json:"humidity"`
	LightIntensity float64   `gorm:"column:light_intensity" json:"light_intensity"`
	WaterPh        float64   `gorm:"column:water_ph" json:"water_ph"`
	Water1Rate     float64   `gorm:"column:water1_rate" json:"water1_rate"`
	Water1Start    time.Time `gorm:"column:water1_start" json:"water1_start"`
	Water1Stop     time.Time `gorm:"column:water1_stop" json:"water1_stop"`
	Water2Rate     float64   `gorm:"column:water2_rate" json:"water2_rate"`
	Water2Start    time.Time `gorm:"column:water2_start" json:"water2_start"`
	Water2Stop     time.Time `gorm:"column:water2_stop" json:"water2_stop"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName HouseLog's table name
func (*HouseLog) TableName() string {
	return TableNameHouseLog
}
