// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name            string         `gorm:"column:name;not null" json:"name"`
	Email           string         `gorm:"column:email;not null" json:"email"`
	EmailVerifiedAt *time.Time      `gorm:"column:email_verified_at" json:"email_verified_at"`
	Password        string         `gorm:"column:password;not null" json:"password"`
	RememberToken   string         `gorm:"column:remember_token" json:"remember_token"`
	IsActive        int32          `gorm:"column:is_active" json:"is_active"`
	RoleID          int32          `gorm:"column:role_id" json:"role_id"`
	CreatedAt       time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
